version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vlog-mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: vlog
    volumes:
      - vlog-mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  vlog-mysql-data:
